### ISSUE TITLE
fix to throw detection

### ISSUE THREAD

**Issue by naxwell** [ThomasJnLiu/VRBowling#1]
add 2 bools to beginning of script

    public bool wasGrabbed = false;
    public bool isGrabbed;

in update, change to the code below 

        isGrabbed = grabber.isGrabbed;

        if (!isGrabbed && wasGrabbed) {
            //set velocity to speed of player's hand
            velocity = playerHand.newSpeed * 1000;
            //write velocity to canvas
            objectPos.text = velocity.ToString();
            //add velocity to object
            rbd.AddForce(transform.forward * velocity);
        }

        wasGrabbed = isGrabbed;

**Comment by ThomasJnLiu** [comment]
Thanks for the fix, Max!
